# Generated by Django 4.2.3 on 2023-07-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
